### ISSUE TITLE
1024M of memory is not enough

### ISSUE THREAD

**Issue by ddpkts** [ongr-io/ongr-sandbox#136] opened 2015-08-20 14:47 UTC
doing composer update with 1024M I get this error https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

updated to 2048M works fine

**Comment by tautrimas** [comment] 2015-09-11 05:27
Duplicate of #120?

**Comment by kazgurs** [comment] 2015-10-08 06:00
Closing together with ongr-io/ongr-sandbox#120

**Closed by kazgurs** 2015-10-08 06:00 UTC
